// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// ============================================================
//  ERC-7857: AI Agents NFT with Private Metadata — Interfaces
// ============================================================

// --------------- Shared enums & structs ---------------------

/// @notice Verification oracle type
enum OracleType {
    TEE,
    ZKP
}

/// @notice Access proof signed by the receiver (or delegated access assistant)
/// @param oldDataHash Hash of the current (old) ciphertext
/// @param newDataHash Hash of the new ciphertext after re-encryption
/// @param nonce       Replay-prevention nonce
/// @param encryptedPubKey Receiver's public key used to encrypt the new data key.
///        Empty means "use receiver's Ethereum public key"
/// @param proof       Signature bytes
struct AccessProof {
    bytes32 oldDataHash;
    bytes32 newDataHash;
    bytes nonce;
    bytes encryptedPubKey;
    bytes proof;
}

/// @notice Ownership proof generated by TEE/ZKP prover
struct OwnershipProof {
    OracleType oracleType;
    bytes32 oldDataHash;
    bytes32 newDataHash;
    bytes sealedKey;      // new data key sealed for receiver
    bytes encryptedPubKey; // receiver's public key
    bytes nonce;
    bytes proof;
}

/// @notice Combined proof required for a secure transfer
struct TransferValidityProof {
    AccessProof accessProof;
    OwnershipProof ownershipProof;
}

/// @notice Decoded output from verifyTransferValidity
struct TransferValidityProofOutput {
    bytes32 oldDataHash;
    bytes32 newDataHash;
    bytes sealedKey;
    bytes encryptedPubKey;
    bytes wantedKey;
    address accessAssistant;
    bytes accessProofNonce;
    bytes ownershipProofNonce;
}

/// @notice A single piece of intelligent data attached to a token
struct IntelligentData {
    string dataDescription;
    bytes32 dataHash;
}

// --------------- Data Verifier interface --------------------

interface IERC7857DataVerifier {
    /// @notice Verify that all proofs are valid and that the new ciphertexts
    ///         are available in storage.  Consumes the nonces (replay protection).
    function verifyTransferValidity(
        TransferValidityProof[] calldata _proofs
    ) external returns (TransferValidityProofOutput[] memory);
}

// --------------- Metadata interface -------------------------

interface IERC7857Metadata {
    function name() external view returns (string memory);
    function symbol() external view returns (string memory);

    /// @notice Return the intelligent data array for a token
    function intelligentDataOf(
        uint256 _tokenId
    ) external view returns (IntelligentData[] memory);
}

// --------------- Main NFT interface -------------------------

interface IERC7857 {
    // ---- Events ----
    event Approval(
        address indexed _from,
        address indexed _to,
        uint256 indexed _tokenId
    );
    event ApprovalForAll(
        address indexed _owner,
        address indexed _operator,
        bool _approved
    );
    event Authorization(
        address indexed _from,
        address indexed _to,
        uint256 indexed _tokenId
    );
    event AuthorizationRevoked(
        address indexed _from,
        address indexed _to,
        uint256 indexed _tokenId
    );
    event Transferred(
        uint256 _tokenId,
        address indexed _from,
        address indexed _to
    );
    event Cloned(
        uint256 indexed _tokenId,
        uint256 indexed _newTokenId,
        address _from,
        address _to
    );
    event PublishedSealedKey(
        address indexed _to,
        uint256 indexed _tokenId,
        bytes[] _sealedKeys
    );
    event DelegateAccess(address indexed _user, address indexed _assistant);

    // ---- State-changing ----
    function iTransfer(
        address _to,
        uint256 _tokenId,
        TransferValidityProof[] calldata _proofs
    ) external;

    function iClone(
        address _to,
        uint256 _tokenId,
        TransferValidityProof[] calldata _proofs
    ) external returns (uint256 _newTokenId);

    function authorizeUsage(uint256 _tokenId, address _user) external;

    function revokeAuthorization(uint256 _tokenId, address _user) external;

    function approve(address _to, uint256 _tokenId) external;

    function setApprovalForAll(address _operator, bool _approved) external;

    function delegateAccess(address _assistant) external;

    // ---- View ----
    function verifier() external view returns (IERC7857DataVerifier);

    function ownerOf(uint256 _tokenId) external view returns (address);

    function authorizedUsersOf(
        uint256 _tokenId
    ) external view returns (address[] memory);

    function getApproved(uint256 _tokenId) external view returns (address);

    function isApprovedForAll(
        address _owner,
        address _operator
    ) external view returns (bool);

    function getDelegateAccess(address _user) external view returns (address);
}
